services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs2024Q1-service
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/home/node/src
    restart: on-failure
